# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ba8cbd11e6e0f570bf105aaaff67176f"
name = "Announcement-Bar-App"
handle = "announcement-bar-app-20"
application_url = "https://indicating-safer-specialty-imagine.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://indicating-safer-specialty-imagine.trycloudflare.com/auth/callback", "https://indicating-safer-specialty-imagine.trycloudflare.com/auth/shopify/callback", "https://indicating-safer-specialty-imagine.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
